"""add resource tables and quiz routes

Revision ID: 724d26b00f67
Revises: db100af64136
Create Date: 2026-02-26 11:41:53.828424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724d26b00f67'
down_revision = 'db100af64136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Enum('PDF', 'CODE', 'IMAGE', 'AUTRE', name='filetypeenum'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('matiere', sa.String(length=100), nullable=True),
    sa.Column('niveau', sa.String(length=10), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_ratings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'user_id', name='uq_resource_user_rating')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_ratings')
    op.drop_table('resources')
    # ### end Alembic commands ###
